### ISSUE TITLE
Compute slopes for each segments/sub-segments

### ISSUE THREAD

**Issue by lbell** [Luuka/GPXParser.js#11]
I'm looking for a GPX parser with a specific functionality, and this looks like it might get me on the right track:

I need to calculate the climb (slope, grade, percent, or like) for each segment of a track (either by node, or by a user-selected distance... say, give me the slope for every 1m segment, or 10m segment, or 100m segment.

Do you think that would be possible / not too difficult to implement?

**Comment by Luuka** [comment]
The calcul of the slope between each points of a track is in my To-Do list, and it's not hard to do.

For the second request, about the user-selected distance, it could be a little bit harder. GPX points are usually not separated by a same/fixed distance. Using a precise interval is harder. 

What would be the use-case ? 
- for a mountain pass, an average of the slopes from sub-segments between two points could be useful
- for a basic interpolation, the absolute slope between two points could be a possibility

**Comment by lbell** [comment]
Wouldn't need to be exact... just thinking of how to  chunk up the line in discreet chunks. Distance-based would be one way. Or altitude based (ever 1m or 10m gain or loss).

**Comment by Luuka** [comment]
Hi ! A basic slope support has been added

**Comment by lbell** [comment]
Awesome! Thanks!
