### ISSUE TITLE
parse not found ??

### ISSUE THREAD

**Issue by MichaelLiss** [Luuka/GPXParser.js#13]
Hi again,

**I am only using Node.js to run the gpxparser.  there is NO client side code at all.**

Per your instruction, I installed via NPM:

C:\Users\mliss\Documents\GitHub\myProject>npm install gpxparser
npm WARN myeventtimes@0.1.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ gpxparser@3.0.0
added 1 package from 1 contributor and audited 404 packages in 5.092s
found 2 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

It seemed to install ??

My useage:

at the top of my file:
let gpx = require('gpxparser');

In my function:

    var fName = '';
    fName = path.join(__dirname, './running.gpx');

    var content = utilityFile.readTextFile_Sync(fName);

    gpx.parse(content);
    var totalDistance = gpx.tracks[0].distance.total;
    console.log('running total distance ' + totalDistance);

-
but I am getting this error when debugging:

TypeError: gpx.parse is not a function

??

**Comment by Luuka** [comment]
Hi again !

You need to instantiate the parser before using it :)

``` js
let gpxParser = require('gpxparser');
let parser = new gpxParser();
parser.parse('<gpx></gpx>');

console.log('running total distance ' + parser.tracks[0].distance.total);
```

I know that this way of using it is a little bit hard to understand, and I'm planning to refactor it in the near future.

**Comment by MichaelLiss** [comment]
Hey...

Will there be any issues if I do that globally and then reuse the parser within functions?

In other words at top of my file:

let gpxParser = require('gpxparser');
let parser = new gpxParser();

func1 = () =>{
  parser.parse(...):
}

func2 = () =>{
  parser.parse(...):
}

**Comment by MichaelLiss** [comment]
whoa... something new now:

ReferenceError: window is not defined
    at gpxParser.parse (c:\Users\mliss\Documents\GitHub\instanttiming\node_modules\gpxparser\dist\GPXParser.min.js:1:216)

**Comment by Luuka** [comment]
Hi, sorry for the late reply.

About your first question, the parse method will not reset the gpx object. So the result of the second call will be an addition of the two calls. I think you must instantiate two `gpxParser`. I think I will refactor this in the future to get something easier to use.

For your second question, I totally forgot this point sorry. The library use a DOMParser and some others DOM related functions, so you must use a Window object Polyfill (https://www.npmjs.com/package/window) to use browser features on your node.js code. 

You can add these lines at the beginning of your code :
```js
const Window = require('window');
global.window = new Window();
```

**Comment by dscape** [comment]
@Luuka why don't you add this to the readme? Or the the if where you do the check for `module`?

**Comment by Luuka** [comment]
FYI, a new version has been published on GH & NPM.
It fix the node.js support issue by including the jsdom polyfill in the dependencies, and as @dscape suggested the initialization of the polyfill is automatic on a Node.js context.

Thanks for your report ! :)
