### ISSUE TITLE
Zero values for elevation break calculations

### ISSUE THREAD

**Issue by JonDHo** [Luuka/GPXParser.js#21]
If an elevation value is a legitimate "0" (rare but possible), [L163](https://github.com/Luuka/GPXParser.js/blob/2dd253f95acc04106fc35dcefc3f8a6af85e10c6/src/GPXParser.js#L163) causes the value to convert to a null. This subsequently breaks the elevation calculations because the null is later run through another `parseFloat` at [L297](https://github.com/Luuka/GPXParser.js/blob/2dd253f95acc04106fc35dcefc3f8a6af85e10c6/src/GPXParser.js#L297), resulting in a NaN, which gets added to the `elevation` object. Subsequently, the `Math.max` and `Math.min` functions on [L302](https://github.com/Luuka/GPXParser.js/blob/2dd253f95acc04106fc35dcefc3f8a6af85e10c6/src/GPXParser.js#L302) and [L303](https://github.com/Luuka/GPXParser.js/blob/2dd253f95acc04106fc35dcefc3f8a6af85e10c6/src/GPXParser.js#L303) return Nulls.

A simple solution for [L163](https://github.com/Luuka/GPXParser.js/blob/2dd253f95acc04106fc35dcefc3f8a6af85e10c6/src/GPXParser.js#L163) to allow zeros is:
```
pt.ele = parseFloat(keepThis.getElementValue(trkpt, "ele")) ?? null;
```
or something else if `??` is too permissive or not widespread enough yet.

**Comment by JonDHo** [comment]
or perhaps change [L163](https://github.com/Luuka/GPXParser.js/blob/2dd253f95acc04106fc35dcefc3f8a6af85e10c6/src/GPXParser.js#L163) to 
```
pt.ele = parseFloat(keepThis.getElementValue(trkpt, "ele"));
pt.ele = isNaN(pt.ele) ? null : pt.ele;
```

**Comment by Luuka** [comment]
Hi ! Thanks for the report, I made a fix. 

It's already available on the master branch and NPM :)
