### ISSUE TITLE
npm package is massive

### ISSUE THREAD

**Issue by andrashann** [Luuka/GPXParser.js#23]
After installing this package via `npm install --save gpxparser`, it adds 8.7 MB of data to the `node_modules` folder, as it contains its own `node_modules` folder as well as the doc, demo, and test folders. Unfortunately, I am unfamiliar with node and how this can be avoided, so I cannot create a pull request to fix this.

**Comment by webjay** [comment]
You could try via `yarn`:

- yarn autoclean --init 
- yarn autoclean --force

**Comment by Luuka** [comment]
Hello,

Lighten the package was in my plan from a long time. 
With the 3.0.8 I removed doc and demo folder to move it to a specific branch. I kept the test folder for the moment, I must search how I can remove it without issues.

It decreased the package from 4.45 MB to 151 kB. :rocket:

**Comment by JasperH8g** [comment]
FYI: The easiest way to exclude files from a released package is by including an [npmignore](https://npm.github.io/publishing-pkgs-docs/publishing/the-npmignore-file.html) file.
